name: "Release"

on:
  push:
    tags: [ "v*" ]

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v3
        with:
          go-version: 1.17

      - name: Kill any existing GPG agent
        run: gpgconf --kill gpg-agent

      - name: Configure GPG agent
        run: |
          eval $(gpg-connect-agent --quiet /bye)
          export GPG_TTY=$(tty)
          export SSH_AUTH_SOCK="$(gpgconf --list-dirs agent-ssh-socket)"
          mkdir -p ~/.gnupg
          echo "use-agent" > ~/.gnupg/gpg.conf
          echo "default-cache-ttl 7200" > ~/.gnupg/gpg-agent.conf
          echo "max-cache-ttl 7200" >> ~/.gnupg/gpg-agent.conf

      - uses: hashicorp/ghaction-import-gpg@v2.1.0
        id: import_gpg
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          PASSPHRASE: ${{ secrets.PASSPHRASE }}

      - uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
